### ISSUE TITLE
Ava: Binary and Styling

### ISSUE THREAD

**Issue by avabrooks** [sarahwxie/ketoswags_spring_portfolio#17]
- [x] Make one controller for main.java
- [x] [Add paper bag to nav bar as 'cart' for user experience](https://github.com/sarahwxie/ketoswags_spring_portfolio/commit/c9092702f469023f7e606fa9ba5177446dd24e05)
- [x] Uniform background color for all site
- [x] Start Binary mini lab
  - [x] Import Mortensen Code
  - [x] Create route 
  - [x] [Customize to fridges](https://github.com/sarahwxie/ketoswags_spring_portfolio/commit/954968d5cb03be5180602814472723e38f46960f)
  - [x] [Start Bits work](https://github.com/sarahwxie/ketoswags_spring_portfolio/commit/7fcdf3fe191243f2d31b7dc269f33e46a1c69bf7)
    - [x] Frontend
    - [x] [Backend](https://github.com/sarahwxie/ketoswags_spring_portfolio/blob/master/src/main/java/com/example/sping_portfolio/Main.java#L26-L29)
- [x] Fix login nav bar issue

**Comment by jm1021** [comment]
Nice design and links to show progress.
