### ISSUE TITLE
Teacher Review Week 4

### ISSUE THREAD

**Issue by crystalwidjaja** [sarahwxie/ketoswags_spring_portfolio#23]

**Comment by jm1021** [comment]
You need some to do's to describe some future ideas.   Not 100A% clear on what people are doing now.   .9 / 1.0

**Comment by jm1021** [comment]
General comments.   1st off the README needs some help.   The POP Quiz section (Persistent Stats)  is supposed to be right below you project introduction.  After which you should have a Time Box section that summarizes Week 4, then Week 3, ...   We are trying to build a COMPLETE history of your project.   This Issue could be "Grading" in the Time Box for week 4.  Video should be linked in Week 4 as well.

**Comment by jm1021** [comment]
Sarah, thank you for filling role of Scrum Master.  In this roles, if you linked me to README when you are ready it could reduce you slack message to "Review Week 4 on README (link)"

Regarding Video, it did an amazing job of show Team Work and accomplishments by each individual.   I really like how you made the Binary with logical increments.  The cards are looking nice on the PBL.  Showing commits for each individual with informative messages was fantastic.  This is a HUGE complement to my review as I know that your team UNDERSTANDS critical portions of my evaluation. 2/2 on Team points.

**Comment by jm1021** [comment]
Ava,
I found [this ticket](https://github.com/sarahwxie/ketoswags_spring_portfolio/issues/17), it instantly earned 2/2 for individual.   It shows working approach and lots of evidence.

Journal is not much to talk about, I would like to see some notes on TPT or TT, as well as any insights or learning after you finish taking AP tests.  4.5/50

In your case, a great place to link TPT presentation would be your journal.

**Comment by jm1021** [comment]
Risa,
I did not find a ticket for you in Review column.  Also, ticket "In progress" shows no progress or work.   Sarah, did share a commit that looked relevant in video.   1/2 on individual.  

Journal is same as Ava.  A kind 4/5 of 5 because of score and remember to add link.  This will go down next time.  

In your case, a great place to link TPT presentation would be your journal.

**Comment by jm1021** [comment]
Crystal,
I see link on find database and checklist on login page (no tangibles).  1.75/2

Your shared journal is nice with some key notes from Uni 4.  I could see some notes from Tech Talk or TPT in future 5/5

**Comment by jm1021** [comment]
Sarah,
The review column has similar checklist but no tangibles. 1.75/2
Journal is same as Crystal 5/5

**Comment by jm1021** [comment]
README is big thing that needs work.  Some tuning required on how you show tangibles easily for review.  Mostly, everything is amazing.

**Comment by jm1021** [comment]
Oh, you need to CLOSE some issues.  That will support your README completed button well.

**Comment by jm1021** [comment]
Please add this issue to README Time Box  for week under "review"
